# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ab9dc694f75b73b43d03904e807e461a77539db7231a06bb1b0c101f2386379445ffd71089fd92c3640de4baae2f664ca2440bb83683d400f40d0444fd4f408

test:
  secret_key_base: 37b308bf93f0dd24ffaa6f1249971b5d20e9eac7fef7ca5e81433b4dc71134551f0a5fb6c5ee55e936f5ad44ffa62b805528484bb48a7c803906298d511a56bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
